apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ptl24v9v3-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.xjiang1118416.jgt9.p3.openshiftapps.com/rhtap/rhtap-qe:b01473631e676b361de711713ee317ff6005c9a8@sha256:3344e0a3f65e22844e804ac6b2650f6c9748da3e65dbafb11b0dad5654ac66f8
          name: container-image
